### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by craibo** [CyrisXD/love-lock-card#19]
After every refersh of the dashbaord this message is displayed:

<img width="459" alt="image" src="https://user-images.githubusercontent.com/2648164/199855613-58a6ddf9-bc47-4fad-85f6-7c66e57efdef.png">

Triggering another refersh if in a web browser results in the component rendering correctly:

<img width="465" alt="image" src="https://user-images.githubusercontent.com/2648164/199855777-2b9bb608-7d62-4a21-8b6b-2d019def82da.png">

If I remove the love-lock-card config then the card loads 100% everytime.

Dashboard card yaml
```
type: vertical-stack
cards:
  - type: custom:love-lock-card
    popup: confirm
    cards:
      - type: custom:mushroom-lock-card
        entity: lock.nuki_front_door_lock
        name: Front Door
        tap_action:
          action: none
```
