### ISSUE TITLE
Custom element doesn't exist: hui-map-card.

### ISSUE THREAD

**Issue by jacauc** [CyrisXD/love-lock-card#27]
Trying to add a map behind one of the lock cards, but I get the following message.
`Custom element doesn't exist: hui-map-card.`

I cleared caches and refreshed resources, but to no avail.

This is my code
```
type: custom:love-lock-card
popup: timeout
cards:
  - type: map
    entities:
      - entity: person.user1
    hours_to_show: 24
    theme_mode: auto
    title: user1
    auto_fit: true
```
any ideas?
