### ISSUE TITLE
Issue: format?

### ISSUE THREAD

**Issue by Sturmhorst** [CyrisXD/love-lock-card#7]
Where is my failure? 

```
password: 1234
popup: password
title: Lounge
type: 'custom:love-lock-card'
cards:
   entities:
     - entity: sensor.pihole_status
     - entity: sensor.pihole_version
     - entity: input_boolean.disable_pihole
   show_header_toggle: false
   title: PiHole
   type: entities
```
![image](https://user-images.githubusercontent.com/43591902/87250352-795af800-c464-11ea-80ad-e54d1d82c45d.png)

**Comment by acordill** [comment]
Needs to be:
```yaml 
password: 1234
popup: password
title: Lounge
type: 'custom:love-lock-card'
cards:
   - entities:
       - entity: sensor.pihole_status
       - entity: sensor.pihole_version
       - entity: input_boolean.disable_pihole
     show_header_toggle: false
     title: PiHole
     type: entities
```
Notice the '-' before entities under cards
